@startuml

title __REPOSITORY's Class Diagram__\n

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface BookRepository {
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface BookToCartItemRepository {
            {abstract} + deleteByCartItem()
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface CartItemRepository {
            {abstract} + findByShoppingCart()
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface OrderRepository {
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface PasswordResetTokenRepository {
            {abstract} + findByToken()
            {abstract} + findByUser()
            {abstract} + findAllByExpiryDateLessThan()
            {abstract} + deleteAllExpiredSince()
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface RoleRepository {
            {abstract} + findByname()
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface ShoppingCartRepository {
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface UserPaymentRepository {
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface UserRepository {
            {abstract} + findByUsername()
            {abstract} + findByEmail()
        }
      }
    }
  }
  

  package  {
    package com.bookstore {
      package com.bookstore.repository {
        interface UserShippingRepository {
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
